"""
Data schema definitions for Agent communication.

This module defines the unified request and response data structures
used across all Agent implementations in the IntelliSearch system.
"""

from pydantic import BaseModel, Field
from typing import Any, Dict


class AgentRequest(BaseModel):
    """
    Unified input container for Agent inference.

    This model encapsulates the input structure for all agent types.
    It requires a prompt and allows flexible metadata for agent-specific
    configuration.

    Attributes:
        prompt: User input instruction or question
        metadata: Agent-specific configuration parameters (e.g., max_iterations,
                 search_engine, temperature, etc.)

    Example:
        >>> request = AgentRequest(
        ...     prompt="Search for recent AI papers",
        ...     metadata={"max_iterations": 5, "search_engine": "google"}
        ... )
    """

    prompt: str = Field(..., description="User input instruction or question")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Agent-specific configuration (e.g., max_iterations, search_engine)",
    )


class AgentResponse(BaseModel):
    """
    Unified output container for Agent inference results.

    This model standardizes the response structure across all agent types.
    It provides status information, the main answer, and flexible metadata
    for intermediate results and debugging information.

    Attributes:
        status: Execution status (e.g., 'success', 'failed', 'timeout')
        answer: Final text response generated by the Agent
        metadata: Intermediate execution data (e.g., sources, thought_log,
                 tool_calls, tokens_used, etc.)

    Example:
        >>> response = AgentResponse(
        ...     status="success",
        ...     answer="I found 5 relevant papers...",
        ...     metadata={"sources": ["arxiv.com/..."], "tokens_used": 1500}
        ... )
    """

    status: str = Field(
        ..., description="Execution status (e.g., 'success', 'failed', 'timeout')"
    )
    answer: str = Field(..., description="Final text response generated by the Agent")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Intermediate execution data (e.g., sources, thought_log, tool_calls)",
    )
